name: Terraform Deploy #infrasture deployment pipeline

on: # what is triggering this specific for the workflow to run
  push: #event
    branches: #can have multiple branches
      - main #should already exist
  pull_request: #pull request for specific branch
    branches: #name-specific
      - main
  workflow_dispatch: #creates a manual physical button on guthub page to allow you to manually push or pull; manually run this workflow

jobs: #consists of steps
  infra-deploy:
    runs-on: ubuntu-latest #runner; who will execute this jobs

    steps:
    - name: clone-codebase
      uses: actions/checkout@v2 #preconfigured action that allows you to clone ur repo

    - name: install Terraform
      uses: hashicorp/setup-terraform@v1 #action is uses; uses this action to setup terraform
      with: #installs specific version for this action; parameters for action
        terraform_version: 1.1.0
    
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
        aws-region: us-east-1
    
    - name: terraform init #follow terraform format: init, validate, plan, then apply
      id: init
      run: terraform init
      working-directory: terraform

    - name: terraform validate
      id: validate
      run: terraform validate
      working-directory: terraform

    - name: terraform plan
      id: plan
      run: terraform plan
      working-directory: terraform

    - name: terraform apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: terraform